name: dask-elearn
channels:
  - conda-forge
dependencies:
  - python=3.9
  - bokeh=2.4
  - dask=2022.6.1
  - dask-labextension
  - distributed=2022.6.1
  - matplotlib
  - pandas=1.4
  - pip
  - python-graphviz
  - ipycytoscape
  - pyarrow
  - s3fs
  - jupyterlab=3
  - h5py
  - holidays
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - dask-ml
  - ipywidgets>=7.5
  - zarr
  - coiled
